version: '0.1'

services:
  api:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8080", "--reload-dir", "/app"]